### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#787]
In order to collaborate with more people, permissions should allow sharing data between institutions/working groups.
The current institution filter makes this impossible. Use case: a member of ChitDB group (set as primary database) adds new public image. A user with primary group GIT, but who is also in Django group ChitDB, cannot see the record in table view and not in detail view. Also, it does not help if assigning permissions for specific users and groups; see the record: https://edit2.geocollections.info/attachment/190890  
At least in detail view, it should be possible to restrict access according to Django permissions and without the additional institution filter.

**Comment by enmust** [comment]
This if clause https://github.com/geocollections/rwapi/blob/main/api/v0/views.py#L210C29-L210C29

**Comment by Erikdzo** [comment]
The user should now be able to switch between the groups they have been assigned to from the app bar. The current implementation has a caveat. Users do not have a good way to look all the data they have access to in a combined form. They can look at one group at a time. 

I added the parameter `all_databases` to the api that shows everything the user has access to, but trying to implement it into the front-end seems painful, as we could need to modify most of the requests in the codebase. Maybe it would be better if there was an option in the group selection that showed everything. The implementation could be for example that we change the user's selected database in the back-end into `null`, which would mean show everything the user has access to. That way we could leave the front-end basically as it currently is. 

Furthermore, the links to an object protected by object permissions should be reviews, as some of them should probably allow for more than one link to be added. For example this is currently a problem in the the reference detail view, where the current implementation allows for only one digital PDF to be added. Only one group might have access to this PDF and the other groups cannot see that file or add their own file into the database (which would be very confusing and frustrating.) On the other hand, if multiple files can be added, do we link all the files in the public portal? And does adding multiple files break the current implementation in the public api?

Users should probably see the public data from the groups that they are not apart of. This would help to reduce the amount of duplicate pdfs or images that would be uploaded otherwise.

**Comment by Erikdzo** [comment]
> The implementation could be for example that we change the user's selected database in the back-end into null, which would mean show everything the user has access to. That way we could leave the front-end basically as it currently is.

One problem I did not think of at first is that, while view items this is not a problem, but when creating objects the `database` field is populated with the value of user's `database` field. If the user has selected to view all databases in the frontend, this value would be populated with `null`, which probably will cause some problems. The only way I could currently think of fixing it would be that the user has to select the database manually in the process of creating the object. But this should only happen if no specific group is selected. Any ideas on a better solution?
